-- SEQUENCES

-- SECUENCIA PARA EL USUARIO
CREATE SEQUENCE seq_usuario
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECUENCIA PARA EL ROL
CREATE SEQUENCE seq_rol
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECUENCIA PARA EL USUARIO CON ROL
CREATE SEQUENCE seq_usuario_rol
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECUENCIA PARA LA ASISTENCIA
CREATE SEQUENCE seq_asistencia
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECUENCIA PARA LA SEDE
CREATE SEQUENCE seq_sede
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECUENCIA PARA EL QR
CREATE SEQUENCE seq_qr_token
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECUENCIA PARA LA JUSTIFICACION
CREATE SEQUENCE seq_justificacion
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECUENCIA PARA LOG ASISTENCIA
CREATE SEQUENCE seq_log_asistencia
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECUENCIA PARA LOG JUSTIFICACION
CREATE SEQUENCE seq_log_justificacion
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;